services:
  healthchecks-ts:
    extends: 
      file: ../ts-compose.yml
      service: ts
    container_name: healthchecks-ts
    hostname: healthchecks
    volumes:
      - /mnt/user/appdata/tailscale/healthchecks:/config
      - /dev/net/tun:/dev/net/tun
    
  healthchecks:
    image: lscr.io/linuxserver/healthchecks:latest
    network_mode: service:healthchecks-ts
    container_name: healthchecks
    depends_on:
      - healthchecks-ts
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
      - SITE_ROOT=https://healthchecks.squeaker-boga.ts.net
      - SITE_NAME=\\\ healthchecks ///
      - SUPERUSER_EMAIL=friesen.josephc@gmail.com
      - SUPERUSER_PASSWORD=healthchecks
      - ALLOWED_HOSTS= #optional
      - APPRISE_ENABLED=False #optional
      - CSRF_TRUSTED_ORIGINS= #optional
      - DEBUG=True #optional
      - DEFAULT_FROM_EMAIL= #optional
      - EMAIL_HOST= #optional
      - EMAIL_PORT= #optional
      - EMAIL_HOST_USER= #optional
      - EMAIL_HOST_PASSWORD= #optional
      - EMAIL_USE_TLS= #optional
      - INTEGRATIONS_ALLOW_PRIVATE_IPS= #optional
      - PING_EMAIL_DOMAIN= #optional
      - RP_ID= #optional
      - SECRET_KEY= #optional
      - SITE_LOGO_URL= #optional
    volumes:
      - /mnt/user/appdata/healthchecks:/config
    labels:
      - "net.unraid.docker.icon=https://images.saasworthy.com/tr:w-200,h-140,c-at_max,e-sharpen-1/healthchecksio_4288_logo_1569304919_zldos.jpg?cm-ext"
      - "net.unraid.docker.managed=dockerman"
      - "net.unraid.docker.webui=https://healthchecks.squeaker-boga.ts.net"
    restart: unless-stopped
