services:
  sonarr-ts:
    extends: 
      file: ../ts-compose.yml
      service: ts
    container_name: sonarr-ts
    hostname: sonarr
    volumes:
      - /mnt/user/appdata/tailscale/sonarr:/config
      - /dev/net/tun:/dev/net/tun
    
  sonarr:
    image: lscr.io/linuxserver/sonarr
    network_mode: service:sonarr-ts
    container_name: sonarr
    depends_on:
      - sonarr-ts
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Los_Angeles
    labels:
      - "net.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-logo.png"
      - "net.unraid.docker.managed=dockerman"
      - "net.unraid.docker.webui=https://sonarr.squeaker-boga.ts.net"
    volumes:
      - /mnt/user/downloads:/downloads
      - /mnt/user/Media/TEEV:/tv
      - /mnt/user/appdata/sonarr:/config
    restart: unless-stopped
    
secrets:
  ts_authkey:
    file: /mnt/user/appdata/tailscale/ts_authkey
