services:
  ts:
    image: tailscale/tailscale:v1.78.3
    environment:
      TS_AUTHKEY: /run/secrets/ts_authkey
      TS_STATE_DIR: /config/state
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      TS_SERVE_CONFIG: /config/serve.json
    secrets:
      - ts_authkey
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped

  secrets:
    ts_authkey:
      file: /mnt/user/appdata/tailscale/ts_authkey
