services:
  searxng:
    container_name: search
    image: docker.io/searxng/searxng:latest
    volumes:
      - /mnt/user/appdata/searxng:/etc/searxng:rw
    environment:
      - TZ=America/Los_Angeles
      - SEARXNG_BASE_URL=https://search.squeaker-boga.ts.net
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    ports:
      - '3818:8080'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped
    labels:
      - tsdproxy.enable=true
      - tsdproxy.ephemeral=false

  searxng-redis:
    container_name: searxng-redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

volumes:
  valkey-data2:
